### ISSUE TITLE
Icons on tabs are not displayed correctly

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/swrltab-plugin#6]
When I open SWRLTab or SQWRLTab (1.0.0-beta-7) in Protege 5.0.0-beta-21 in Ubuntu, I see that the icons on the internal tabs are incorrectly displayed (basically they are overlapped with the tab name, making the the tab name unreadable).
This could be a more general problem introduced with the update of the tab rendering in Protege 5.0.0-beta-16 (see also protegeproject/protege#143).

![swrltab_icons](https://cloud.githubusercontent.com/assets/2441046/12661125/a75f343c-c5cc-11e5-889e-39f227bdbef4.png)

**Comment by martinjoconnor** [comment]
This works fine in the standalone version of the SWRLTab so it must be some sort of Protege-specific tab rendering setting. 

I can try to center them to see if that would override the default, which should be easy - though I am wondering if this would be working around a deeper problem that other plugins will also see. 

My code for adding a tab is plain vanilla Swing:

    addTab("Inferred Axioms", this.owl2RLIcon, inferredOWLAxiomsView, "Inferred OWL Axioms Tab");

Here, addTab is the JTabbedPane method.

**Comment by matthewhorridge** [comment]
They are customised tabs in Protege.  It might be easier and best to just get rid of the icons.

**Comment by matthewhorridge** [comment]
... I mean get rid of them in Protege... i.e. prevent Protege from painting them.

**Comment by martinjoconnor** [comment]
So - should I just kill them in the SWRLTab tabs? They are not especially meaningful in the places that I use them.

**Comment by matthewhorridge** [comment]
> So - should I just kill them in the SWRLTab tabs? They are not especially meaningful in the places that I use them.

That's up to you, but if you don't think they are meaningful anyway then I would get rid of them.

**Comment by martinjoconnor** [comment]
Got rid of them. New 1.0.0-beta-8 up there.

FYI, may get something like the following error when updating plugin but works fine on restart. Some setting clearly wrong somewhere in the plugin manifest I'd guess.

----------------------- Downloading and Installing Plugin ---------------------- 
Downloading the SWRLTab plugin (Version 1.0.0.beta-8) 
Downloading the SWRLTab plugin from: https://github.com/protegeproject/swrltab-plugin/releases/download/swrltab-plugin-1.0.0-beta-8/swrltab-plugin-1.0.0-beta-8.jar 
The SWRLTab plugin has been downloaded to /var/folders/8l/wnqvbzx946v278f218v8pq5w0000gn/T/swrltab1943532688428512949.jar 
Copied the SWRLTab plugin to swrltab.jar in the plugins directory 
Installing the SWRLTab plugin 
An error occurred whilst installing the SWRLTab plugin.  This error was caused because the version of this plugin (1.0.0.beta-8)was either missing some other components that are not installed or, more likely,it is not compatible with this version of Protégé. 
org.osgi.framework.BundleException: Unresolved constraint in bundle swrltab-plugin [32]: Singleton conflict.
